version: '3.8'

services:
  flask_app:
    build: ./flask_app
    image: gunjanpandya/flask_app:latest
    ports:
      - "3000:3000"
    volumes:
      - ./flask_app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key-please-change-in-production
      - PYTHONUNBUFFERED=1
    networks:
      - app_network
    restart: unless-stopped

  django_app:
    build: ./django_app
    image: gunjanpandya/django_app:latest
    ports:
      - "8000:8000"
    volumes:
      - ./django_app:/app
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge